config/routes.rb
Rails.application.routes.draw do
  resources :cats, :cat_rental_requests
end

app/models/cat.rb
COLORS = ["brown", "black", "red", "blue", "orange", "white", "gray", "purple", "green"]

class Cat < ActiveRecord::Base
  validates :birthdate, :color, :name, :sex, :description, presence: true
  validates :color, inclusion: COLORS

  has_many :cat_rental_requests,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :CatRentalRequest,
    dependent: :destroy

end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  validates :end_date, :start_date, :cat_id, :status, presence: true
  validate :does_not_overlap_approved_request


  belongs_to :cat,
    primary_key: :id,
    foreign_key: :cat_id,
    class_name: :Cat

  def overlapping_requests
    CatRentalRequest
      .where.not(id: self.id)
      .where(cat_id: cat_id)
      .where(<<-SQL, start_date: start_date, end_date: end_date)
        NOT( (start_date > :end_date) OR (end_date < :start_date))
    SQL
  end

  def overlapping_approved_requests
    self.overlapping_requests.where(status: :APPROVED)
  end

  def does_not_overlap_approved_request
    if self.overlapping_approved_requests.exists?
      self.status = "DENIED"
      # errors[:base] << "there are overlapping approved requests!"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController

  def new
    @cats = Cat.all
    render :new
  end

  def create
    @rent = CatRentalRequest.new(request_params)
    if @rent.save
      redirect_to cat_url(request_params[:cat_id])
    else
      render :new
    end
  end

  private

  def request_params
    params.require(:rent).permit(:cat_id, :start_date, :end_date)
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    render :index
  end

  def show
    @cat = Cat.find_by(id: params[:id])
    if @cat
      render :show
    else
      redirect_to cats_url
    end
  end

  def new
    @cat = Cat.new
    render :new
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      redirect_to cats_url
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find_by(id: params[:id])
    render :edit
  end

  def update
    @cat = Cat.find_by(id: params[:id])

    if @cat.update_attributes(cat_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end

  private
  def cat_params
    params.require(:cat).permit(:name, :birthdate, :sex, :color, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_request_helper.rb
module CatRentalRequestHelper
end

app/helpers/cats_controller_helper.rb
module CatsControllerHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>New Rental Request</h1>

<form action= <%= cat_rental_requests_url %> method="POST">
  Select Cat:
  <select name = "rent[cat_id]">
    <option disabled selected>-- Select Cat --</option>
    <% @cats.each do |cat| %>
      <option value=" <%= cat.id %> "><%= cat.name %></option>
    <% end %>
  </select>
  <br><br>
  Select Start Date:
  <input type="date" name="rent[start_date]">
  <br><br>
  Select End Date:
  <input type="date" name="rent[end_date]">
  <br><br>
  <input type="submit" value="Submit Request">
</form>

app/views/cats/_cat.html.erb
<li>
  <%= cat.name %>
</li>

app/views/cats/_form.html.erb
<% if action == :edit %>
  <% action_url = cat_url(cat) %>
<% else %>
  <% action_url = cats_url %>
<% end %>

<form action=<%= action_url %> method="POST">
  <% if action == :edit %>
    <input type="hidden" name='_method' value = "PATCH">
  <% end %>
  Name:
  <input type="text" name="cat[name]" value="<%= cat.name %>">
  <br><br>Sex: <br>
  <input <%= cat.sex == "M" ? "checked" : "" %> type="radio" name="cat[sex]" value="M">Male<br>
  <input <%= cat.sex == "F" ? "checked" : "" %> type="radio" name="cat[sex]" value="F">Female<br>
  <input <%= cat.sex == "O" ? "checked" : "" %> type="radio" name="cat[sex]" value="O">Other<br>
  <br>
  Color:
  <select name = cat[color]>
    <option selected disabled>-- Please Select Color --</option>
    <option <%= cat.color == "brown" ? "selected" : "" %> value="brown">Brown</option>
    <option <%= cat.color == "black" ? "selected" : "" %> value="black">Black</option>
    <option <%= cat.color == "red" ? "selected" : "" %> value="red">Red</option>
    <option <%= cat.color == "blue" ? "selected" : "" %> value="blue">Blue</option>
    <option <%= cat.color == "orange" ? "selected" : "" %> value="orange">Orange</option>
    <option <%= cat.color == "white" ? "selected" : "" %> value="white">White</option>
    <option <%= cat.color == "gray" ? "selected" : "" %> value="gray">Gray</option>
    <option <%= cat.color == "purple" ? "selected" : "" %> value="purple">Purple</option>
    <option <%= cat.color == "green" ? "selected" : "" %> value="green">Green</option>
  </select>
  <br><br>
  Birthdate:
  <input value='<%= cat.birthdate %>' type="date" name="cat[birthdate]">
  <br><br>
  Description:<br>
  <textarea name="cat[description]" rows="8" cols="80"><%= cat.description %></textarea>

  <input type="submit">
</form>

app/views/cats/edit.html.erb
<h1>Edit ze Cat</h1>

<%= render 'form', action: :edit, cat: @cat %>

app/views/cats/index.html.erb
<h1>All cats in Arlen</h1>

<%=render @cats%>

app/views/cats/new.html.erb
<h1>Add a new Cat to Arlen</h1>

<%= render 'form', action: :new, cat: @cat %>

app/views/cats/show.html.erb
<h1>CAT</h1>
<table>
  <colgroup>
    <col style="background-color: #0f0">
    <col style="background-color: #0f0">
    <col style="background-color: #0f0">
    <col style="background-color: #0f0">
    <col style="background-color: #0f0">
  </colgroup>
  <tr>
    <th>Name</th>
    <th>Birthdate</th>
    <th>Color</th>
    <th>Sex</th>
    <th>Description</th>
  </tr>
  <tr>
    <td><%= @cat.name%></td>
    <td><%= @cat.birthdate%></td>
    <td><%= @cat.color%></td>
    <td><%= @cat.sex%></td>
    <td><%= @cat.description%></td>
  </tr>

</table>
<table>
  <tr>
    <th>start_date</th>
    <th>end_date</th>
  </tr>

    <% @cat.cat_rental_requests.each do |request| %>
    <tr>
    <td><%= request.start_date %></td>
    <td><%= request.end_date%> </td>
    <% end %>
  </tr>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>